CREATE OR REPLACE PACKAGE PR_TABLE_DATA AS

PROCEDURE INSERT_DATA;

END PR_TABLE_DATA;

/


CREATE OR REPLACE PACKAGE BODY PR_TABLE_DATA AS

PROCEDURE INSERT_DATA IS


cursor C1 is

			SELECT DISTINCT SUPPLIER_NAME,

				SUBSTR(SUPP_CONTACT_NAME, 1, INSTR(SUPP_CONTACT_NAME, ' ')-1) AS FRIST_NAME,

				SUBSTR(SUPP_CONTACT_NAME, INSTR(SUPP_CONTACT_NAME, ' ')+1) AS LAST_NAME,

				SUPP_ADDRESS, 

				REPLACE(TRIM(SUBSTR(SUPP_CONTACT_NUMBER, 1, INSTR(SUPP_CONTACT_NUMBER, ',')-1)),' ') AS TEL_NUMBER,

				REPLACE(TRIM(SUBSTR(SUPP_CONTACT_NUMBER, INSTR(SUPP_CONTACT_NUMBER, ',')+1)),' ') AS MOBILE_PHONE,

				SUPP_EMAIL

			FROM XXBCM_ORDER_MGT

			WHERE NOT EXISTS (SELECT 1 

								FROM XXBCM_SUPPLIER_TBL 

								WHERE XXBCM_SUPPLIER_TBL.SUPPLIER_NAME = XXBCM_ORDER_MGT.SUPPLIER_NAME)
             AND REPLACE(TRIM(SUBSTR(SUPP_CONTACT_NUMBER, 1, INSTR(SUPP_CONTACT_NUMBER, ',')-1)),' ') = REGEXP_SUBSTR ( REPLACE(TRIM(SUBSTR(SUPP_CONTACT_NUMBER, 1, INSTR(SUPP_CONTACT_NUMBER, ',')-1)),' '), '[0-9]{7}+')	
             AND REPLACE(TRIM(SUBSTR(SUPP_CONTACT_NUMBER, INSTR(SUPP_CONTACT_NUMBER, ',')+1)),' ') = REGEXP_SUBSTR (REPLACE(TRIM(SUBSTR(SUPP_CONTACT_NUMBER, INSTR(SUPP_CONTACT_NUMBER, ',')+1)),' '), '[0-9]{8}+');


CURSOR C2 IS 
SELECT DISTINCT
ORDER_REF 			
       ,SUPPLIER_NAME 		
       ,ORDER_DATE 			
       ,NVL(REPLACE(ORDER_TOTAL_AMOUNT,','),0) AS ORDER_TOTAL_AMOUNT
       ,ORDER_DESCRIPTION 
       ,ORDER_STATUS 		
       ,NVL(REPLACE(ORDER_LINE_AMOUNT,','),0) AS ORDER_LINE_AMOUNT
FROM XXBCM_ORDER_MGT
WHERE NOT EXISTS (SELECT 1 

								FROM XXBCM_ORDER_TBL 

								WHERE XXBCM_ORDER_TBL.ORDER_REF = XXBCM_ORDER_MGT.ORDER_REF)
AND EXISTS (SELECT 1 

								FROM XXBCM_SUPPLIER_TBL 

								WHERE XXBCM_SUPPLIER_TBL.SUPPLIER_NAME = XXBCM_ORDER_MGT.SUPPLIER_NAME)
  AND NVL(REPLACE(ORDER_TOTAL_AMOUNT,','),0) = REGEXP_SUBSTR ( NVL(REPLACE(ORDER_TOTAL_AMOUNT,','),0), '[0-9]+')              
 AND NVL(REPLACE(ORDER_LINE_AMOUNT,','),0) = REGEXP_SUBSTR ( NVL(REPLACE(ORDER_LINE_AMOUNT,','),0), '[0-9]+')
 ORDER BY ORDER_REF;
								
								
CURSOR C3 IS 
SELECT INVOICE_REFERENCE 	  
       ,ORDER_REF 			
       ,TO_DATE(INVOICE_DATE,'DD-MM-YYYY') AS INVOICE_DATE
       ,INVOICE_STATUS 		
       ,INVOICE_HOLD_REASON
       ,NVL(REPLACE(INVOICE_AMOUNT ,','),0) AS INVOICE_AMOUNT
       ,INVOICE_DESCRIPTION
FROM XXBCM_ORDER_MGT
WHERE NOT EXISTS (SELECT 1 

								FROM XXBCM_INVOICE_TBL 

								WHERE XXBCM_INVOICE_TBL.INVOICE_REFERENCE = XXBCM_ORDER_MGT.INVOICE_REFERENCE
                AND XXBCM_INVOICE_TBL.ORDER_REF = XXBCM_ORDER_MGT.ORDER_REF)
AND EXISTS (SELECT 1 

								FROM XXBCM_ORDER_TBL 

								WHERE XXBCM_ORDER_TBL.ORDER_REF = XXBCM_ORDER_MGT.ORDER_REF)
AND INVOICE_REFERENCE IS NOT NULL
AND NVL(REPLACE(INVOICE_AMOUNT,','),0) = REGEXP_SUBSTR ( NVL(REPLACE(INVOICE_AMOUNT,','),0), '[0-9]+');


BEGIN

		for A in C1 loop	


					INSERT INTO XXBCM_SUPPLIER_TBL VALUES (A.SUPPLIER_NAME, A.FRIST_NAME, A.LAST_NAME,

					A.SUPP_ADDRESS, A.TEL_NUMBER, A.MOBILE_PHONE, A.SUPP_EMAIL);

		end LOOP;
		
		
		FOR B IN C2 loop
		
			INSERT INTO XXBCM_ORDER_TBL VALUES ( DEFAULT,
			B.ORDER_REF 			
       ,B.SUPPLIER_NAME 		
       ,TO_DATE(B.ORDER_DATE,'DD-MON-YYYY') 			
       ,TO_NUMBER(B.ORDER_TOTAL_AMOUNT)
       ,B.ORDER_DESCRIPTION 
       ,B.ORDER_STATUS 		
       ,TO_NUMBER(B.ORDER_LINE_AMOUNT)
			);
		
		END LOOP;
		
		
		FOR C IN C3 loop
		
			INSERT INTO XXBCM_INVOICE_TBL VALUES ( DEFAULT,
				C.INVOICE_REFERENCE 	  
				,C.ORDER_REF 			
				,C.INVOICE_DATE 		
				,C.INVOICE_STATUS 		
				,C.INVOICE_HOLD_REASON
				,TO_NUMBER(C.INVOICE_AMOUNT)		
				,C.INVOICE_DESCRIPTION
			);
		
		END LOOP; 

		COMMIT;

END INSERT_DATA;

END PR_TABLE_DATA;

--EXEC PR_TABLE_DATA.INSERT_DATA;