-- TABLE NORMALISATION

  CREATE TABLE XXBCM_ORDER_MGT 
   (	
	ORDER_REF 			VARCHAR2(2000), 
	ORDER_DATE 			VARCHAR2(2000), 
	SUPPLIER_NAME 		VARCHAR2(2000), 
	SUPP_CONTACT_NAME 	VARCHAR2(2000), 
	SUPP_ADDRESS 		VARCHAR2(2000), 
	SUPP_CONTACT_NUMBER VARCHAR2(2000), 
	SUPP_EMAIL 			VARCHAR2(2000), 
	ORDER_TOTAL_AMOUNT 	VARCHAR2(2000), 
	ORDER_DESCRIPTION 	VARCHAR2(2000), 
	ORDER_STATUS 		VARCHAR2(2000), 
	ORDER_LINE_AMOUNT 	VARCHAR2(2000), 
	INVOICE_REFERENCE 	VARCHAR2(2000), 
	INVOICE_DATE 		VARCHAR2(2000), 
	INVOICE_STATUS 		VARCHAR2(2000), 
	INVOICE_HOLD_REASON VARCHAR2(2000), 
	INVOICE_AMOUNT 		VARCHAR2(2000), 
	INVOICE_DESCRIPTION VARCHAR2(2000)
   ) ;
	
	CREATE TABLE XXBCM_SUPPLIER_TBL
   (
	SUPPLIER_NAME 		VARCHAR2(1000) NOT NULL, 
	FIRST_NAME 	VARCHAR2(500)  NOT NULL,
	LAST_NAME 	VARCHAR2(500)  NOT NULL,	
	SUPP_ADDRESS 		VARCHAR2(2000),
	TEL_NUMBER VARCHAR2(7),
	MOBILE_NUMBER VARCHAR2(8), 	
	SUPP_EMAIL_ADD 			VARCHAR2(200),
	CONSTRAINT XXBCM_SUPPLIER_PK PRIMARY KEY (SUPPLIER_NAME)
    ) ;
	

CREATE TABLE XXBCM_ORDER_TBL
   (
	ORDER_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    ORDER_REF 			VARCHAR2(15) NOT NULL, 
	SUPPLIER_NAME 		VARCHAR2(1000) NOT NULL,
	ORDER_DATE 			DATE,
	ORDER_TOTAL_AMOUNT 	NUMERIC(15,2), 
	ORDER_DESCRIPTION 	VARCHAR2(2000), 
	ORDER_STATUS 		VARCHAR2(15), 
	ORDER_LINE_AMOUNT 	NUMERIC(15,2),
	CONSTRAINT XXBCM_ORDER_PK PRIMARY KEY (ORDER_ID, ORDER_REF),
	CONSTRAINT XXBCM_SUPPLIER_FK FOREIGN KEY (SUPPLIER_NAME) REFERENCES XXBCM_SUPPLIER_TBL (SUPPLIER_NAME)
    ) ;
	
	
	CREATE TABLE XXBCM_INVOICE_TBL
   (
    INVOICE_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	INVOICE_REFERENCE 	VARCHAR2(2000) NOT NULL, 
	ORDER_REF 			VARCHAR2(15) NOT NULL,
	INVOICE_DATE 		DATE, 
	INVOICE_STATUS 		VARCHAR2(15), 
	INVOICE_HOLD_REASON VARCHAR2(200), 
	INVOICE_AMOUNT 		NUMERIC(15,2), 
	INVOICE_DESCRIPTION VARCHAR2(2000),
	CONSTRAINT XXBCM_INVOICE_ORD_PK PRIMARY KEY (INVOICE_ID,INVOICE_REFERENCE,ORDER_REF)
	--CONSTRAINT XXBCM_ORDER_FK FOREIGN KEY (ORDER_REF) REFERENCES XXBCM_ORDER_TBL (ORDER_REF)
    ) ;